apiVersion: v1
kind: Secret
metadata:
  name: banvic-postgres-secret
  namespace: banvic
type: Opaque
stringData:
  POSTGRES_DB: banvic_database
  POSTGRES_USER: banvic
  POSTGRES_PASSWORD: banvic_dev