apiVersion: v1
kind: Service
metadata:
  name: banvic-postgres
  namespace: banvic
spec:
  selector:
    app: banvic-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP