apiVersion: v1
kind: Secret
metadata:
  name: banvic-postgres-connection
  namespace: banvic
type: Opaque
stringData:
  POSTGRES_HOST: "$(POSTGRES_HOST)"
  POSTGRES_PORT: "$(POSTGRES_PORT)"
  POSTGRES_DB: "$(POSTGRES_DB)"
  POSTGRES_USER: "$(POSTGRES_USER)"
  TARGET_POSTGRES_PASSWORD: "$(TARGET_POSTGRES_PASSWORD)"
  TARGET_POSTGRES_SQLALCHEMY_URL: "postgresql+psycopg://$(POSTGRES_USER):$(TARGET_POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
