apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-scheduler
  namespace: banvic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-meltano-runner
  namespace: banvic
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-meltano-runner
  namespace: banvic
subjects:
  - kind: ServiceAccount
    name: airflow-scheduler
    namespace: banvic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-meltano-runner
